# Generated by Django 5.0.6 on 2024-06-03 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionHotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoServicio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField()),
                ('tarifa', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_list', to='gestionHotel.hotel')),
            ],
        ),
    ]
