# Generated by Django 5.0.6 on 2024-06-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionHotel', '0002_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tarifa',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('duracion', models.TimeField()),
                ('categoria', models.CharField(max_length=50)),
                ('beneficios', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquete_list', to='gestionHotel.hotel')),
                ('servicio', models.ManyToManyField(related_name='paquete_list', to='gestionHotel.servicio')),
            ],
        ),
    ]
