# Generated by Django 5.0.6 on 2024-06-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionHotel', '0004_alter_paquete_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada')], default='Disponible', max_length=15)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitacion_list', to='gestionHotel.hotel')),
            ],
        ),
    ]
