# Generated by Django 5.0.6 on 2024-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionHotel', '0005_habitacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='capacidad',
            new_name='capacidadPersonas',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='numeroBaños',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='numeroCamas',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada')], default='Disponible', max_length=15),
        ),
    ]
