# Generated by Django 5.0.6 on 2024-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionHotel', '0006_rename_capacidad_habitacion_capacidadpersonas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada')], default='Disponible', max_length=15),
        ),
    ]
