# Generated by Django 5.0.6 on 2024-06-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionHotel', '0011_habitacion_codigo_habitacion_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='codigo',
            new_name='numeroHabitacion',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada')], default='Disponible', max_length=15),
        ),
    ]
